### ISSUE TITLE
MathJax exponent causes not interpretatioin

### ISSUE THREAD

**Issue by zerbfra** [ClockworkEngine/LightPaper-Support#35]
Hi.
Try this:
$$ x_1 r^2   $$

The r^2 is interpreted as markdown and not mathjax and the expressions results uninterpreted.

**Comment by gaspaio** [comment]
I have the same problem. No mathjax for me ...

**Comment by rasbt** [comment]
Same problem for me, but when I manually inserted the MathJax script (see below, from https://docs.mathjax.org/en/v2.6-latest/start.html) it seems to work.

<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>

**Comment by RoyiAvital** [comment]
Hi,
Where did you insert it?

**Comment by rasbt** [comment]
@RoyiAvital I just inserted it at the beginning of the document

![screen shot 2015-10-15 at 9 30 59 am](https://cloud.githubusercontent.com/assets/5618407/10515063/96790030-731f-11e5-92f2-50290fe4e545.png)

![screen shot 2015-10-15 at 9 31 12 am](https://cloud.githubusercontent.com/assets/5618407/10515059/90e0af10-731f-11e5-8310-a05b575dc083.png)

**Comment by RoyiAvital** [comment]
@rasbt, Is it documented?
Namely, the documentation suggests to do so?
I though Math should work out of the box.

Thank YOu.

**Comment by rasbt** [comment]
@RoyiAvital No, I don't think so; like you said it should work right out of the box. I think it's a bug, and I just inserted it "manually" as a temporary workaround.

**Comment by RoyiAvital** [comment]
So why was it closed?

**Comment by rasbt** [comment]
@RoyiAvital I was wondering too.

Btw. I just looked at the top of this thread again and saw that @zerbfra has inserted whitespaces before and after `$$`. Typically, you don't use whitespaces between the content and the delimiters since most markdown editors wouldn't strip the additional whitespace which would cause problems with mathjax. 

When you remove the whitespaces, you can see that it is doing something, namely, replacing the `$$`s by `\[` and `\]`

![screen shot 2015-10-16 at 9 24 19 pm](https://cloud.githubusercontent.com/assets/5618407/10556277/0e82cc90-744d-11e5-99dc-85c74ea1856a.png)

![screen shot 2015-10-16 at 9 24 31 pm](https://cloud.githubusercontent.com/assets/5618407/10556281/15029082-744d-11e5-8709-7f7e62b9fec5.png)

So, it seems  it got the typical mathjax configuration implemented 


	  </pre> 
	    <script type="text/x-mathjax-config">
	    MathJax.Hub.Config({
	        tex2jax: {
	            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
	            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
	            processEscapes: true,
	            processEnvironments: true
	        },
	        // Center justify equations in code and markdown cells. Elsewhere
	        // we use CSS to left justify single line equations in code cells.
	        displayAlign: 'center',
	        "HTML-CSS": {
	            styles: {'.MathJax_Display': {"margin": 0}},
	            linebreaks: { automatic: true }
	        }
	    });
	    </script></pre>

But it is not loading the mathjax JS. Maybe this is intended?

**Comment by ashokgelal** [comment]
The reason why MathJAX is broken right now is because they changed their old JavaScript CDN link. Thankfully you can embedd "raw" JavaScript in LightPaper. You all might be happy to know that after a looong break, I've restarted to work on LightPaper again. This and many other bugs have already been fixed.
